name: Docs

on:
  [push, pull_request]

defaults:
  run:
    shell: bash

jobs:

  ### SasView Tests (runs on matrix of OSes)

  docs:

    runs-on: ubuntu-latest

    steps:

    - name: Obtain SasView source from git
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    ### Setup environment for building/testing sasview

    - name: Install build and test dependencies
      uses: ./.github/actions/common-setup
      with:
        os: ubuntu-latest
        python-version: 3.8


    ### Build sasview and documentation

    - name: Build sasview
      run: |
        # SET SASVIEW GITHASH
        githash=$( git rev-parse HEAD )
        sed -i.bak s/GIT_COMMIT/$githash/g src/sas/sasview/__init__.py
        # BUILD SASVIEW
        python setup.py clean
        python setup.py build
        python -m pip install .

    - name: Build sasmodels and bumps docs
      run: |
        make -C ../bumps/doc html || true
        mkdir -p ~/.sasmodels/compiled_models
        make -j4 -C ../sasmodels/doc html || true

    - name: Build sasview docs
      run: |
        cd docs/sphinx-docs/
        xvfb-run -a --server-args="-screen 0 1024x768x24" python build_sphinx.py || true
