name: Tests

on:
  [push, pull_request]

defaults:
  run:
    shell: bash

jobs:

  ### SasView Tests (runs on matrix of OSes)

  tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:

    - name: Obtain SasView source from git
      uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    ### Setup environment for building/testing sasview

    - name: Install build and test dependencies
      uses: ./.github/actions/common-setup
      with:
        os: ${{ matrix.os }}
        python-version: ${{ matrix.python-version }}

    ### Actual building/testing of sasview

    - name: Build sasview
      run: |
        # SET SASVIEW GITHASH
        githash=$( git rev-parse HEAD )
        sed -i.bak s/GIT_COMMIT/$githash/g src/sas/sasview/__init__.py
        # BUILD SASVIEW
        python setup.py clean
        python setup.py build
        python -m pip install .

    - name: Test with pytest
      env:
        PYOPENCL_COMPILER_OUTPUT: 1
      run: |
        python -m pytest -v -s test

    - name: Test GUI (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      env:
        PYOPENCL_COMPILER_OUTPUT: 1
      run: |
        cd src/sas/qtgui
        xvfb-run -a --server-args="-screen 0 1024x768x24" python GUITests.py || true
